<?php require_once("../includes/settings.php") ?><?php require_once("../includes/header.php") ?><div id="navigation"><h3>Credits</h3><?php require_once("../includes/navbar.php") ?></div><div id="main"><h4>For details on the algorithm behind Jester, please see:</h4>

<p><a href="http://www.ieor.berkeley.edu/~goldberg/pubs/eigentaste.pdf" target="_blank">Eigentaste: A Constant Time Collaborative Filtering Algorithm.</a></p>



<p><font size="1"> Ken Goldberg, Theresa Roeder, Dhruv Gupta, and Chris Perkins. 
Information Retrieval, 4(2), 133-151. July 2001.</p></font>

<h4>Jester 4.0 Project Team:</h4><p><a href="http://goldberg.berkeley.edu" target="_blank">Ken Goldberg</a>, Tavi Nathanson, <a href="http://www.ocf.berkeley.edu/~ebitton/" target="_blank">Ephrat Bitton</a></p><p class="endsection"></p><h4>Jester 3.0 Project Team:</h4><p><a href="http://goldberg.berkeley.edu" target="_blank">Ken Goldberg</a>, Robert Hennessy</p><p class="endsection"></p><h4>Jester 2.0 Project Team:</h4><p><a href="http://goldberg.berkeley.edu" target="_blank">Ken Goldberg</a>, Dhruv Gupta, Chris Perkins</p><p class="endsection"></p><h4>Jester 1.0 Project Team:</h4><p><a href="http://goldberg.berkeley.edu" target="_blank">Ken Goldberg</a>, Dhruv Gupta, Hiro Narita, Mark DiGiovanni</p><p class="endsection"></p><h4>We thank:</h4><p>Richard Wallace, Hal Varian, Vivek Sanghi, Carol Kirschenbaum, Avi Goldberg, David Pescovitz, Bob Farzin, Adam Jacobs, Derek Poon, and Cathie Walker</p><p class="endsection"></p><h4>Press:</h4><ul><li><a href="http://www.alumni.berkeley.edu/California/200903/praxisfool.asp" target="_blank">California Magazine: <i>Foolproof funny: better humor through computer science</i></a>, 3/20/09</li><li><a href="http://chronicle.com/wiredcampus/article/?id=2860" target="_blank">Wired Campus: <i>Web Site at U. of California at Berkeley Tailors Jokes to Individual Tastes</i></a>, 4/1/08</li></ul><p class="endsection"></p><h4>Reviews:</h4><ul><li><a href="http://www.makeuseof.com/tag/8-best-daily-jokes-sites-to-lighten-up-your-mood/" target="_blank">MakeUseOf: <i>8 Best Daily Jokes Sites To Lighten Up Your Mood</i></a>, 2/3/09</li></ul><p class="endsection"></p><h4>Eigentaste:</h4><p>Eigentaste, the algorithm that powers Jester, was developed at UC Berkeley by <a href="http://goldberg.berkeley.edu" target="_blank">Prof. Ken Goldberg</a> et. al. To learn more about it, go <a href="http://eigentaste.berkeley.edu/info.php" target="_blank">here</a>.</p><p class="endsection"></p><h4>More Information:</h4><p>For more information, see the following paper:</p><p><a href="http://www.eecs.berkeley.edu/Pubs/TechRpts/2009/EECS-2009-85.html" target="_blank">Algorithms, Models and Systems for Eigentaste-Based Collaborative Filtering and Visualization</a><br />Tavi Nathanson. Master's thesis, EECS Department, University of California, Berkeley, May 2009.</p></div><?php require_once("../includes/footer.php") ?>
